openapi: 3.0.3
info:
  title: Backstage Notifications Plugin - OpenAPI Specs
  description: |-
    Backstage Notifications Plugin - OpenAPI Specs
  version: 1.0.0
tags:
  - name: notifications
    description: Backstage notifications plugin
paths:
  /notifications:
    post:
      tags:
        - notifications
      summary: Create notification
      description: Create notification
      operationId: createNotification
      requestBody:
        description: Create a new notification
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  messageId:
                    type: string
                    example: bc9f19de-8b7b-49a8-9262-c5036a1ed35e
    get:
      tags:
        - notifications
      summary: Gets notifications
      description: Gets notifications
      operationId: getNotifications
      parameters:
        - name: user
          in: query
          description: User for whom notifications will be fetched
          required: true
          schema:
            type: string
        - name: pageSize
          in: query
          description: Page size of the result
          required: true
          schema:
            type: integer
        - name: pageNumber
          in: query
          description: Page number of the result
          required: true
          schema:
            type: integer
        - name: read
          in: query
          description: Notifications read or not
          required: true
          schema:
            type: boolean
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notifications'
        '500':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Notifications:
      type: array
      items:
        $ref: '#/components/schemas/Notification'
    Action:
      properties:
        id:
          type: string
          example: aaf2e18f-fa55-4dd4-8d71-58878b4398ad
        url:
          type: string
          example: http://foo.bar
        title:
          type: string
          example: my-title
    Notification:
      properties:
        id:
          type: string
          example: 19d76846-4bce-4786-bdc0-e44c30756dec
        created:
          type: string
          format: date-time
          example: "2023-11-21T15:33:15.800Z"
        isSystem:
          type: boolean
          example: false
        readByUser:
          type: boolean
          example: false
        origin:
          type: string
          example: my-origin
        title:
          type: string
          example: My message title
        message:
          type: string
          format: nullable
          example: I have nothing to say
        topic:
          type: string
          format: nullable
        targetUsers: # Used in Post Notifications
          type: array
          format: nullable
          items:
            type: string
            example: jdoe
        targetGroups: # Used in Post Notifications
          type: array
          format: nullable
          items:
            type: string
            example: jdoe
        actions:
          type: array
          format: nullable
          items:
            $ref: '#/components/schemas/Action'
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            name:
              type: string
              example: Error
            message:
              type: string
              example: pageSize and pageNumber must both be either 0 or greater than 0
            stack:
              type: string
              example: >-
                Error: "pageSize and pageNumber must both be either 0 or greater than 0"
        request:
          type: object
          properties:
            method:
              type: string
              example: GET
            url:
              type: string
              example: /notifications?user=jdoe&read=false&pageNumber=-1&pageSize=1
        response:
          type: object
          properties:
            statusCode:
              type: integer
              format: int32
              example: 500
