name: Check trailing white spaces before merge

on:
  pull_request:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/check-whitespace.yaml
      - 'mta-v7.x/**'

jobs:
  check-whitespace:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Get Changed Files
      id: get-changed-files
      uses: tj-actions/verify-changed-files@v20
      with:
        files: |
          **application.properties


    - name: Check white spaces scripts
      env:
        CHANGED_FILES: ${{ steps.get-changed-files.outputs.files }}
      run: |

        tw_lines=""

        for file in $CHANGED_FILES
        do
        lines=$(egrep -rnIH " +$" $file | cut -f-2 -d ":")
        if [ ! -z "$lines" ]; then
            tw_lines+=$([[ -z "$tw_lines" ]] && echo "$lines" || echo $'\n'"$lines")
        fi
        done

        exit_code=0

        # If tw_lines is not empty, change the exit code to 1 to fail the CI.
        if [ ! -z "$tw_lines" ]; then
        echo -e "\n***** Lines containing trailing whitespace *****\n"
        echo -e "${tw_lines[@]}"
        echo -e "\nFailed.\n"
        exit_code=1
        fi

        exit $exit_code


