name: Greeting workflow container image and manifest push

on:
  push:
    branches: [ "main" ]
    paths:
      - 'greeting/**'

jobs:
  call-main-workflow:
    uses: parodos-dev/serverless-workflows/.github/workflows/main.yml@main
    with:
      workflow_id: greeting
    secrets: inherit

