name: Container Images

on:
  push:
    branches: [ "main" ]
env:
  workflow_id: mta
  workflow_version: "0.0.1"
  KN_VERSION: "v1.11.0"
  KN_WORKFLOW_VERSION: "0.32.0"

jobs:
  generate-manifests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: dir
      run: cd ${{ env.workflow_id }} ; ls -la
    - name: setup kn-workflow
      run: curl -L https://github.com/rgolangh/kie-tools/releases/download/0.0.0-fix-kn-workflow/kn-workflow -o kn-workflow && chmod +x kn-workflow
    - name: sanity
      run: pwd; ls -la 
    - name: kn-workflow
      run: cd ${{ env.workflow_id }} && ../kn-workflow gen-manifest
    - name: Archive manifests 
      uses: actions/upload-artifact@v3
      with:
        name: serverless-workflow-${{ env.workflow_id }} 
        path: ${{ env.workflow_id }}/manifests

  build:
    runs-on: ubuntu-latest
    steps:
    - name: ulimit
      run: ulimit
    - uses: actions/checkout@v3
    - name: Buildah Action
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.workflow_id }}
        tags: ${{ github.sha }}
        extra-args: --ulimit nofile=4096:4096
        containerfiles: |
          pipeline/workflow-builder.Dockerfile
        build-args: |
          WF_RESOURCES=${{ env.workflow_id }}/

    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: serverless-workflow-${{ env.workflow_id}}
        tags: ${{ env.workflow_version }}
        registry: quay.io/orchestrator
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"


      
  
