name: MTA workflow container image and manifest push

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'mta/**'

jobs:
  call-main-workflow:
    uses: parodos-dev/serverless-workflows/.github/workflows/main.yml@main
    with:
      workflow_id: mta
      build_arg_quarkus_extensions: kogito-addons-quarkus-jobs-service-embedded
    secrets: inherit

